config/routes.rb
Rails.application.routes.draw do
  # root 'blogs#index'
  root 'homes#index'

  resources :blogs
  get 'search_rakuten_api', to: 'blogs#search_rakuten_api'
  get 'search_plans_api', to: 'blogs#search_plans_api'

  resources :users, only: [:index, :show]

  resources :homes do
    collection do
      post 'results', to: 'homes#results'
      get 'results_2', to: 'homes#results_2'
      get 'index_2', to: 'homes#index_2'
      get 'detail', to: 'homes#detail'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :bigint(8)        not null, primary key
#  title      :string(255)
#  body       :text(65535)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Blog < ApplicationRecord
end

app/models/condition.rb
class Condition
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :area_code, array: :integer
  attribute :play_date, :date
  attribute :min_price, :integer
  attribute :max_price, :integer
  attribute :start_time_zone, array: :integer
  attribute :plan_lunch, :boolean
  attribute :plan_2sum, :boolean
  attribute :plan_caddie, :boolean
  attribute :ng_plan, :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_rakuten_api(keyword = '軽井沢')
    @courses = RakutenWebService::Gora::Course.search(keyword: keyword)
  end

  def search_plans_api
    next_week = Date.today + 7
    chiba_and_kanagawa = '12,14'
    @plans = RWS::Gora::Plan.search(areaCode: chiba_and_kanagawa, playDate: next_week.strftime('%Y-%m-%d'))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :build_condition, only: :results
  before_action :condition_check, only: :results

  NG_PLANS = {
              ng_caddie: 'planCaddie',
              ng_cart: 'planCart',
              ng_stay: 'planStay',
              ng_lesson: 'planLesson',
              ng_open_compe: 'planOpenCompe',
              ng_regular_compe: 'planRegularCompe',
              ng_half_round: 'planHalfRound',
              ng_early: 'planEarly',
            }

  def index
    @condition = Condition.new
  end

  def index_2
  end

  def results
    @plans = search_plans
    cource_ids = @plans.pluck('golf_course_id')
    cources = RakutenWebService::Gora::Course.search(golfCourseId: cource_ids)
    @address_hash =
      cources.each_with_object({}) do |c, hash|
        hash[c.golf_course_id] = c.address
      end
  end

  def detail
    @play_date = params[:play_date]
    @prefecture = params[:prefecture]
    # 80111
    #@cource ||= RakutenWebService::Gora::CourseDetail.find(80111)
     @cource = RakutenWebService::Gora::CourseDetail.find(params[:golf_course_id])
  end

  private

  def conditions_params
    params.require(:condition).permit(
      :play_date,
      :min_price,
      :max_price,
      :plan_caddie,
      :plan_2sum,
      :plan_Lunch,
      :ng_plan,
      area_code: [],
      start_time_zone: [],

      )
  end

  def build_condition
    @condition = Condition.new conditions_params
  end

  def condition_check
    return if @condition.area_code && @condition.play_date
    empty_params = []
    empty_params << 'エリア' if @condition.area_code.blank?
    empty_params << 'プレー日' if @condition.play_date.blank?
    joined_empty_params = empty_params.join(',')
    redirect_to root_path, alert: "#{joined_empty_params}を入力してください"
  end

  def search_plans
    area_code = @condition.area_code.join(',')
    start_time_zone = @condition.start_time_zone&.join(',')
    if @condition.ng_plan
      ng_plans = []
      @condition&.ng_plan.each do |n|
        puts NG_PLANS[n.to_sym]
        ng_plans << NG_PLANS[n.to_sym]
      end
      joined_ng_plans = ng_plans&.join(',')
    end
    RWS::Gora::Plan.search(
        areaCode: area_code,
        playDate: @condition.play_date,
        minPrice: @condition.min_price,
        maxPrice: @condition.max_price,
        startTimeZone: start_time_zone,
        planCaddie: @condition.plan_caddie,
        planLunch: @condition.plan_lunch,
        plan2sum: @condition.plan_2sum,
        NGPlan: joined_ng_plans.presence,
        # NGプラン対象
        # planCaddie：キャディ付
        # planCart：乗用カート有
        # planStay：宿泊プラン
        # planLesson：レッスン
        # planOpenCompe：オープンコンペ 【NEW】
        # planRegularCompe：コンペ【NEW】
        # planHalfRound：9Hプレー
        # planEarly：早朝プレー
        # 例:NGPlan=planCart,planLesson,planHalfRound
      )
    # @plans = RWS::Gora::Plan.search(areaCode: conditions_params['area_code'], playDate: conditions_params['play_date'], minPrice: 0, maxPrice: 25000)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>
<%= link_to 'rakten', search_rakuten_api_path %>
<%= link_to 'plans', search_plans_api_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/search_plans_api.html.slim
= @plans.count
= @plans.first.inspect
/ - @courses.each do |c|
/   p.text-danger= c.evaluation
/   .btn.btn-danger= c.golf_course_name
/   p= c.golf_course_caption
/   p= c.address
/   p= link_to 'リンク', c.golf_course_detail_url, target: "_new"

app/views/blogs/search_rakuten_api.html.slim
= @courses.count
- @courses.each do |c|
  p.text-danger= c.evaluation
  .btn.btn-danger= c.golf_course_name
  p= c.golf_course_caption
  p= c.address
  p= link_to 'リンク', c.golf_course_detail_url, target: "_new"

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/homes/_clubInfo.html.slim
table#courseInfo.panel[style="margin-top: 30px;"]
  caption ゴルフ場情報
  tr
    th ゴルフ場説明文
    td= @cource.golf_course_caption
  tr
    th ゴルフ場からのお知らせ
    td= @cource.information
  tr
    th 電話番号
    td= @cource.telephone_no
  tr
    th 開場日
    td= @cource.open_day
  tr
    th 休場日
    td= @cource.close_day
  tr
    th 使用可能クレジットカード
    td= @cource.credit_card
  tr
    th シューズ指定
    td= @cource.shoes
  tr
    th 服装指定
    td= @cource.dress_code
  tr
    th 付帯施設（練習場）
    td= @cource.practice_facility
  tr
    th 付帯施設(宿泊施設)
    td= @cource.lodging_facility
  tr
    th 付帯施設(その他)
    td= @cource.other_facility
  tr
    th 設計者
    td= @cource.designer
  tr
    th コース種別
    td= @cource.course_type
  tr
    th コース高低
    td= @cource.course_vertical_interval
  tr
    th 面積
    td= @cource.dimension
  tr
    th グリーン
    td= @cource.green
  tr
    th グリーン数
    td= @cource.green_count
  tr
    th ホール数
    td= @cource.hole_count
  tr
    th パー数
    td= @cource.par_count
  tr
    th コース名
    td= @cource.course_name
  tr
    th 距離
    td= @cource.course_distance
  tr
    th ドラコン推奨ホール
    td= @cource.long_driving_contest

app/views/homes/_comment.html.slim
table#comment.panel[style="margin-top: 30px;"]
  caption 評価者のコメント
  tr
    th タイトル
    td= @cource.ratings.first.title
  tr
    th 評価者のニックネーム
    td= @cource.ratings.first.nick_name
  tr
    th 評価者の都道府県
    td= @cource.ratings.first.nick_name
  tr
    th 評価者の年齢
    td= @cource.ratings.first.age
  tr
    th 評価者の性別
    td= @cource.ratings.first.sex
  tr
    th 評価者のGORA利用回数
    td= @cource.ratings.first.times
  tr
    th 評価者の評価（総合）
    td= @cource.ratings.first.evaluation
  tr
    th 評価者の評価（スタッフ）
    td= @cource.ratings.first.staff
  tr
    th 評価者の評価（設備）
    td= @cource.ratings.first.facility
  tr
    th 評価者の評価（食事）
    td= @cource.ratings.first.meal
  tr
    th 評価者の評価（コース）
    td= @cource.ratings.first.course
  tr
    th 評価者の評価(コストパフォーマンス)
    td= @cource.ratings.first.costperformance
  tr
    th 評価者の評価(距離)
    td= @cource.ratings.first.distance
  tr
    th 評価者の評価(フェアウェイの広さ)
    td= @cource.ratings.first.fairway
  tr
    th 評価者のコメント
    td= @cource.ratings.first.comment

app/views/homes/_plan.html.slim
.card
  .flexbox
    span.city= plan['prefecture']
    h2.golf_place= plan['golfCourseName']
  .imagebox
    = image_tag("#{plan["golfCourseImageUrl"]}", class: 'image')

  a= link_to detail_homes_path(golf_course_id: plan['golfCourseId'], play_date: play_date), class: 'click_link' do
    .star[class="star_#{plan['evaluation'].round}"]
      span.rate= plan['evaluation']
    address.address-area= @address_hash["#{plan.golf_course_id}"]
    address.address-way= "#{plan['ic']}ICから#{plan["icDistance"]}"
            / 楽天の料金は正規表現で抽出する。
    ul.price.flexbox
      li
        = image_tag('gdo_logo')
        span.gdo_price 6680円
      li
        = image_tag('jaran_logo')
        span.jaran_price 6680円
      li
        = image_tag('rakuten_logo')
        span.rakuten_price 6680円

        / = plan['displayWeekdayMinPrice']

app/views/homes/_reviews.html.slim
  table#review
    caption クチコミ
    tr
      th クチコミ件数
      td= @cource.rating_num

app/views/homes/index.html.slim
- min_prices = [['5000', 5000], ['10000', 10000], ['15000',15000]]
- max_prices = [['5000', 5000], ['10000', 10000], ['15000',15000]]

#content
  .intro
    p
      | ゴルフ場大手予約サイト3社を比較！
      br>/
      | 最高のプランで最高のゴルフを

  = simple_form_for @condition, url: results_homes_url, html: { id: :areaForm2} do |f|
    /! intro
    section#search
      .inner
        dl#area
          dt エリア
          dd#areaForm 全地域
          = render 'areaselect', f: f
        dl#date
          dt プレー日
          dd
            = f.text_field :play_date, class: 'date-picker'
        = f.button :submit, '検索する'

        /! submit
        .detail_btn
          a.more.btn
            |さらに条件を指定する
            span
            span
        /! detail
        .detail
          dl#price
            dt プレー料金
            dd
              = f.input :min_price, as: :select, collection: min_prices, label: false, prompt: '下限なし'
              span 〜
              = f.input :max_price, as: :select, collection: max_prices, label: false, prompt: '上限なし'

          dl#time
            dt スタート時間
            dd
              ul
                li
                  label[for="condition_start_time_zone_6"] ~6時台
                  = f.check_box :start_time_zone, {multiple: true}, '6', nil
                li
                  label[for="condition_start_time_zone_7"] 7時台
                  = f.check_box :start_time_zone, {multiple: true}, '7', nil
                li
                  label[for="condition_start_time_zone_8"] 8時台
                  = f.check_box :start_time_zone, {multiple: true}, '8', nil
                li
                  label[for="condition_start_time_zone_9"] 9時台
                  = f.check_box :start_time_zone, {multiple: true}, '9', nil
                li
                  label[for="condition_start_time_zone_10"] 10時台
                  = f.check_box :start_time_zone, {multiple: true}, '10', nil
                li
                  label[for="condition_start_time_zone_11"] 11時台
                  = f.check_box :start_time_zone, {multiple: true}, '11', nil
                li
                  label[for="condition_start_time_zone_12"] 12時台
                  = f.check_box :start_time_zone, {multiple: true}, '12', nil
                li
                  label[for="condition_start_time_zone_13"] 13時台~
                  = f.check_box :start_time_zone, {multiple: true}, '13', nil
          dl#option
            dt オプション
            dd
              ul
                li
                  label[for="condition_plan_lunch"] 昼食付き
                  = f.check_box :plan_lunch, {multiple: false}, '1', nil
                li
                  label[for="condition_plan_2sum"] 2サム付き
                  = f.check_box :plan_2sum, {multiple: false}, '2', nil
                li
                  label[for="condition_plan_caddie"] キャディ付き
                  = f.check_box :plan_caddie, {multiple: false},'3', nil

          dl#avoid
            dt 除外指定
            dd#all
              span
              |全て選択
            dd
              ul
                li
                  label[for="ng_half_round"] 9Hプレー
                  = f.check_box :ng_half_round, {multiple: false}, '1', nil
                li
                  label[for="ng_cart"] 乗用カート有
                  = f.check_box :ng_cart, {multiple: false}, nil
                li
                  label[for="ng_lesson"] レッスン
                  = f.check_box :ng_lesson, {multiple: false}, nil
                li
                  label[for="ng_stay"] 宿泊プラン
                  = f.check_box :ng_stay, {multiple: false}, nil
                li
                  label[for="ng_regular_compe"] コンペ
                  = f.check_box :ng_regular_compe, {multiple: false}, nil
                li
                  label[for="ng_caddie"] キャディ付き
                  = f.check_box :ng_caddie, {multiple: false}, nil
      /! detail
    /! inner
    /! search
/! content

javascript:
  var ready;

  ready = function() {
    $('.date-picker').datepicker().datepicker("setDate", new Date());
    var dateFormat;
    dateFormat = 'yy-mm-dd';
    return $('.date-picker').datepicker({
      dateFormat: 'yy/mm/dd (DD)',
      minDate: new Date(),
    });
    $('.date-picker').datepicker("setDate", new Date());
  };

  $(document).ready(ready);

  $(document).on('turbolinks:load', ready);

app/views/homes/index_2.html.slim
/ = simple_form_for :conditions, url: homes_path, html: { id: :areaForm2} do |f|
/   = f.input :area, as: :string
/   = f.input :play_date, as: :date, html5: true
/   = f.button :submit

= form_tag search_homes_url do
  = select :conditions, :area_code, [['北海道', 1], ['青森', 2], ['岩手', 3]]
  = date_field('conditions','play_date')
  = submit_tag '検索'

#content
  .intro
    p
      | ゴルフ場大手予約サイト3社を比較！
      br>/
      | 最高のプランで最高のゴルフを
  /! intro
  section#search
    .inner
      dl#area
        dt エリア
        dd
          form#areaForm
            select name="都道府県"
              option hidden="" value=""  ---
      dl#date
        dt プレー日
        dd
          form#dateForm
            select name="都道府県"
              option hidden="" value=""  ---
              option hidden="" value=""  ---
              option value="0"  全地域
              option value="1"  北海道
              option value="2"  東京
              option value="3"  沖縄
      .submit
        form
          input.btn type="submit" value="検索する" /
      /! submit
      .detail_btn
        p.more.btn
          a さらに条件を指定する
      /! detail
      .detail
        dl#price
          dt プレー料金
          dd
            form#priceMin
              select name="下限なし"
                option hidden="" value=""  下限なし
                option value="0"  5,000
                option value="1"  5,000
                option value="2"  5,000
                option value="3"  5,000
            span 〜
            form#priceMax
              select name="上限なし"
                option hidden="" value=""  上限なし
                option value="0"  5,000
                option value="1"  5,000
                option value="2"  5,000
                option value="3"  5,000
        dl#time
          dt スタート時間
          dd
            ul
              li.active ~6時台
              li 7時台
              li 8時台
              li 9時台
              li 10時台
              li 11時台
              li 12時台
              li 13時台~
        dl#option
          dt オプション
          dd
            ul
              li.active 昼食付き
              li 2サム付き
              li キャディ付き
              li 昼食付き
              li 2サム付き
              li キャディ付き
        dl#avoid
          dt 除外指定
          dd.all 全て選択
          dd
            ul
              li.active 9Hプレー
              li ジュニアプラン
              li レッスン
              li 宿泊プラン
              li 2サム保証
              li キャディ付き
      /! detail
    /! inner
  /! search
  /! 都道府県選択エリア
  .areaSelect
    .overLay
    dl.modalContent
      dt.ttl エリアを選択してください
      dd
        form
          ul
            li
              dl
                dt.subTtl
                  input name="kantou" type="checkbox" value="0" >/
                  | 関東・甲信越
                dd.list
                  span
                    input name="kantou" type="checkbox" value="1" >/
                    | 茨城県
                  span
                    input name="kantou" type="checkbox" value="2" >/
                    | 栃木県
                  span
                    input name="kantou" type="checkbox" value="3" >/
                    | 群馬県
                  span
                    input name="kantou" type="checkbox" value="4" >/
                    | 埼玉県
                  span
                    input name="kantou" type="checkbox" value="5" >/
                    | 千葉県
                  span
                    input name="kantou" type="checkbox" value="9" >/
                    | 長野県
                  span
                    input name="kantou" type="checkbox" value="8" >/
                    | 山梨県
                  span
                    input name="kantou" type="checkbox" value="9" >/
                    | 長野県
                  span
                    input name="kantou" type="checkbox" value="10" >/
                    | 静岡県
                  span
                    input name="kantou" type="checkbox" value="11" >/
                    | 新潟県
            li
              dl
                dt.subTtl
                  input name="kantou" type="checkbox" value="0" >/
                  | 関東・甲信越
                dd.list
                  span
                    input name="kantou" type="checkbox" value="1" >/
                    | 茨城県
                  span
                    input name="kantou" type="checkbox" value="2" >/
                    | 栃木県
                  span
                    input name="kantou" type="checkbox" value="3" >/
                    | 群馬県
                  span
                    input name="kantou" type="checkbox" value="4" >/
                    | 埼玉県
                  span
                    input name="kantou" type="checkbox" value="5" >/
                    | 千葉県
                  span
                    input name="kantou" type="checkbox" value="9" >/
                    | 長野県
                  span
                    input name="kantou" type="checkbox" value="8" >/
                    | 山梨県
                  span
                    input name="kantou" type="checkbox" value="9" >/
                    | 長野県
                  span
                    input name="kantou" type="checkbox" value="10" >/
                    | 静岡県
                  span
                    input name="kantou" type="checkbox" value="11" >/
                    | 新潟県
            li
              dl
                dt.subTtl
                  input name="kantou" type="checkbox" value="0" >/
                  | 関東・甲信越
                dd.list
                  span
                    input name="kantou" type="checkbox" value="1" >/
                    | 茨城県
                  span
                    input name="kantou" type="checkbox" value="2" >/
                    | 栃木県
                  span
                    input name="kantou" type="checkbox" value="3" >/
                    | 群馬県
                  span
                    input name="kantou" type="checkbox" value="4" >/
                    | 埼玉県
                  span
                    input name="kantou" type="checkbox" value="5" >/
                    | 千葉県
                  span
                    input name="kantou" type="checkbox" value="9" >/
                    | 長野県
                  span
                    input name="kantou" type="checkbox" value="8" >/
                    | 山梨県
                  span
                    input name="kantou" type="checkbox" value="9" >/
                    | 長野県
                  span
                    input name="kantou" type="checkbox" value="10" >/
                    | 静岡県
                  span
                    input name="kantou" type="checkbox" value="11" >/
                    | 新潟県
            li
              dl
                dt.subTtl
                  input name="kantou" type="checkbox" value="0" >/
                  | 関東・甲信越
                dd.list
                  span
                    input name="kantou" type="checkbox" value="1" >/
                    | 茨城県
                  span
                    input name="kantou" type="checkbox" value="2" >/
                    | 栃木県
                  span
                    input name="kantou" type="checkbox" value="3" >/
                    | 群馬県
                  span
                    input name="kantou" type="checkbox" value="4" >/
                    | 埼玉県
                  span
                    input name="kantou" type="checkbox" value="5" >/
                    | 千葉県
                  span
                    input name="kantou" type="checkbox" value="9" >/
                    | 長野県
                  span
                    input name="kantou" type="checkbox" value="8" >/
                    | 山梨県
                  span
                    input name="kantou" type="checkbox" value="9" >/
                    | 長野県
                  span
                    input name="kantou" type="checkbox" value="10" >/
                    | 静岡県
                  span
                    input name="kantou" type="checkbox" value="11" >/
                    | 新潟県
  /! 都道府県選択エリア
/! content

app/views/homes/results.html.slim
- plan = @plans.first
- wd = ["日", "月", "火", "水", "木", "金", "土"]
- wday = wd[Time.current.wday]
#contents
  nav
    ul.flexbox
      li
       = image_tag('icon')
       p#place= plan['prefecture']
      li
        = image_tag('icon02')
        p#date= @condition.play_date.strftime("%-m月%-d日(#{wday})")
      li
        button name="button" type="button"
          = image_tag('icon03')
          | 条件を絞り込む
  section
    .main_contents
      .inner
        .find_wrap.flexbox
          p
            span#find= @plans.count
            | 件見つかりました
          select#sort name=""
            option value=""  安い順
            option value=""  高い順
            option value=""  おすすめ順
        #card_wrap
          = render partial: 'plan', collection: @plans, locals: { play_date: @condition.play_date.strftime("%-m月%-d日(#{wday})"), prefecture: plan['prefecture'] }

app/views/homes/reviews.html.slim
  table#review
    caption クチコミ
    tr
      th クチコミ件数
      td= @cource.rating_num

app/views/layouts/_footer.html.slim
footer
  p.Copyright
    | Copyright © 2000-2018 Golf Digest Online Inc. All rights reserved.
div.set_overLay

app/views/layouts/_header.html.slim
nav.navbar.bg-dark.navbar-dark
  h1.logo
    a href="/" = image_tag('logo.gif')

app/views/layouts/application.html.slim
/ 仮デザインです。変更してください
scss:
  .alert {
    background: red;
    color: white;
  }


doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1.0" name="viewport" /
    title Golphin
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    - flash.each do |key, value|
      div[class="alert alert-#{key}"]= value

    .container= yield
    = render 'layouts/footer'

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim